/* FlyFight Zero — original interactive visualization, synthetic RNN and sparse-reward experiment.
   No FlyWire/BANC dataset, biological neuron parameters or trained fly policy are included. */
'use strict';
(() => {
const $=id=>document.getElementById(id),{V,I,mul,T,S:scale,RY,RX,compose,transform,perspective,lookAt,color}=GFX;
const clamp=(x,a,b)=>Math.min(b,Math.max(a,x)),lerp=(a,b,t)=>a+(b-a)*t,TAU=Math.PI*2;
const angleDiff=(a,b)=>Math.atan2(Math.sin(a-b),Math.cos(a-b));
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
const colors={a:color('#67e6ee'),b:color('#f4bb79'),brown:color('#7c4c2b'),tan:color('#bf945b'),dark:color('#2c2823'),leg:color('#92754f'),gun:color('#34414c'),steel:color('#8197a3'),eye:color('#aa3326'),wing:color('#b4ced0',.28)};
const palette=[[.22,.82,.91],[.95,.61,.29],[.31,.61,.78],[.96,.76,.39],[.90,.48,.65]];
class Brain{
 constructor(seed=1){this.n=768;this.seed=seed;this.rand=rng(seed);this.palette=palette;let r=rng(20260914);this.h=new Float32Array(this.n);this.next=new Float32Array(this.n);this.activity=new Float32Array(this.n);this.signedActivity=this.h;this.pos=[];this.region=[];this.ids=[];this.displayEdges=[];this.inIdx=new Uint16Array(this.n*8);this.inW=new Float32Array(this.n*8);this.recIdx=new Uint16Array(this.n*6);this.recW=new Float32Array(this.n*6);this.bias=new Float32Array(this.n);this.history=[];this.mean=0;this.active=0;this.updates=0;this.decisions=0;
 const groups=[{count:150,c:[-1.67,.48,-.08],s:[1.08,.88,.68]},{count:150,c:[1.67,.48,.08],s:[1.08,.88,.68]},{count:138,c:[-.57,.73,.04],s:[.86,.73,.56]},{count:138,c:[.57,.73,-.04],s:[.86,.73,.56]},{count:192,c:[0,-1.05,.10],s:[.86,1.16,.52]}];
 let i=0;groups.forEach((g,gi)=>{for(let j=0;j<g.count;j++,i++){let a=r()*TAU,z=r()*2-1,rad=Math.cbrt(r()),q=Math.sqrt(1-z*z),x=g.c[0]+rad*q*Math.cos(a)*g.s[0],y=g.c[1]+rad*z*g.s[1],depth=g.c[2]+rad*q*Math.sin(a)*g.s[2];if(gi===4)x*=.76+.24*clamp((.25-y)/1.5,0,1);this.pos.push([x,y,depth]);let colorGroup=gi<2?(j%5===0?0:1):gi<4?(j%6===0?1:0):(j%4===0?1:j%7===0?4:0);this.region.push(colorGroup);this.ids.push(`syn-${String(i).padStart(4,'0')}`);}});
 for(let i=0;i<this.n;i++){this.bias[i]=(r()-.5)*.15;for(let j=0;j<8;j++){this.inIdx[i*8+j]=Math.floor(r()*725);this.inW[i*8+j]=(r()*2-1)*.63;}for(let j=0;j<6;j++){let t=r()<.65?clamp(i+Math.floor((r()-.5)*110),0,this.n-1):Math.floor(r()*this.n);this.recIdx[i*6+j]=t;this.recW[i*6+j]=(r()*2-1)*.24;if(j<2)this.displayEdges.push([i,t]);}}
 this.heads=[5,9,9,2];this.out=25;this.stride=this.n+1;this.weights=new Float32Array(this.out*this.stride);this.grad=new Float32Array(this.weights.length);let rw=rng(971);for(let j=0;j<this.weights.length;j++)this.weights[j]=(rw()-.5)*.016;this.lastAction=[0,0,0,0,0];this.probs=[];
 }
 step(pixels,lastAction){let input=new Float32Array(725);input.set(pixels.subarray(0,720));input.set(lastAction,720);for(let i=0;i<this.n;i++){let x=this.bias[i];for(let j=0;j<8;j++)x+=input[this.inIdx[i*8+j]]*this.inW[i*8+j];for(let j=0;j<6;j++)x+=this.h[this.recIdx[i*6+j]]*this.recW[i*6+j];this.next[i]=this.h[i]*.35+Math.tanh(x)*.65;}[this.h,this.next]=[this.next,this.h];this.signedActivity=this.h;for(let i=0;i<this.n;i++)this.activity[i]=Math.abs(this.h[i]);this.stats();this.history.push(Array.from({length:32},(_,j)=>this.activity[Math.floor(j*this.n/32)]));if(this.history.length>40)this.history.shift();this.decisions++;}
 stats(){let total=0,n=0;for(let x of this.activity){total+=x;if(x>.5)n++;}this.mean=total/this.n;this.active=n;}
 regionColor(reg,a){let p=palette[reg%palette.length]||palette[2];return p.map(x=>x*(.37+.9*a)).concat(1);}
 policy(){let features=this.h,selected=[],offset=0;this.probs=[];for(let size of this.heads){let logits=[];for(let a=0;a<size;a++){let o=(offset+a)*this.stride,z=this.weights[o+this.n];for(let i=0;i<this.n;i++)z+=this.weights[o+i]*features[i];logits.push(z);}let m=Math.max(...logits),p=logits.map(x=>Math.exp(x-m)),sum=p.reduce((a,b)=>a+b);p=p.map(x=>x/sum);let v=this.rand(),choice=size-1;for(let a=0;a<size;a++){v-=p[a];if(v<=0){choice=a;break;}}selected.push(choice);this.probs.push(p);for(let a=0;a<size;a++){let err=(choice===a?1:0)-p[a],o=(offset+a)*this.stride;for(let i=0;i<this.n;i++)this.grad[o+i]+=err*features[i];this.grad[o+this.n]+=err;}offset+=size;}
 let move=selected[0],axis=[-1,-.75,-.5,-.25,0,.25,.5,.75,1],action=[move===1?1:move===2?-1:0,move===3?-1:move===4?1:0,axis[selected[1]],axis[selected[2]],selected[3]];this.lastAction=action;return action;
 }
 reward(r){if(r!==0){let sq=0;for(let v of this.grad)sq+=v*v;let f=.015*r*Math.min(1,5/(Math.sqrt(sq)||1));for(let i=0;i<this.weights.length;i++)this.weights[i]=clamp(this.weights[i]+f*this.grad[i],-2,2);this.updates++;}this.grad.fill(0);}
 resetEpisode(){this.h.fill(0);this.next.fill(0);this.grad.fill(0);this.lastAction=[0,0,0,0,0];}
}
let renderer;
try{renderer=new GFX.Renderer($('gl'));}catch(e){$('errorMessage').textContent=e.message;$('error').style.display='grid';return;}
const state={mode:'showcase',paused:false,speed:1,t:0,roundTime:0,round:1,score:[0,0],duration:60,tick:0,intermission:0,shots:[],sparks:[],camera:'duel',az:.60,elev:.94,dist:94,auto:false,brainAngles:[.14,-.14],brainZoom:[1,1],brainEdges:['active','active'],brainPointScale:[1,1],selectedNeurons:[-1,-1],external:false,dataset:null,trace:[],fps:0,renderScale:1,native:false,training:{},policyVersion:0,showPixels:true};
let agents=[],rngScene=rng(711),accumulator=0,last=performance.now(),uiClock=0,obsClock=0,socket=null,lastExternalT=-Infinity,pendingFrame=null,externalHello=false,lastNeuralMatrices=[null,null],dirtyRender=true;
let mapSpec=window.FLYFIGHT_MAP||{id:'fallback',width:64,depth:48,wall_height:5,obstacles:[]};
let obstacles=mapSpec.obstacles.slice();
function setMap(m){if(!m||![m.width,m.depth,m.wall_height].every(Number.isFinite)||m.width<16||m.width>256||m.depth<16||m.depth>256||m.wall_height<=0||m.wall_height>30||!Array.isArray(m.obstacles)||m.obstacles.length>64)throw Error('잘못된 맵');for(let b of m.obstacles)if(!['x','z','w','d','h'].every(k=>Number.isFinite(b[k]))||Math.min(b.w,b.d,b.h)<=0||Math.max(b.w,b.d,b.h)>256)throw Error('잘못된 엄폐물');mapSpec=m;obstacles=m.obstacles.slice();state.dist=Math.max(m.width,m.depth)*1.47;dirtyRender=true;}

function agent(id){let a={id,brain:new Brain(id===0?31:49),x:0,z:0,yaw:0,pitch:0,hp:100,action:[0,0,0,0,0],lastShot:-10,muzzle:0,hitFlash:0,phase:0,moveSpeed:0,shots:0,hits:0,headshots:0,strafe:id===0?1:-1,source:'synthetic'};return a;}
function resetEpisode(){let spawn=rng(200+state.round),flip=state.round%2===0?-1:1;agents.forEach((a,i)=>{a.x=(i===0?-3.5:3.5)*flip;a.z=(spawn()-.5)*3.5;a.yaw=(i===0?Math.PI/2:-Math.PI/2)+(state.mode==='learn'?(spawn()-.5)*TAU:0);a.pitch=0;a.hp=100;a.action=[0,0,0,0,0];a.lastShot=-10;a.muzzle=0;a.moveSpeed=0;a.brain.resetEpisode();});state.roundTime=0;state.intermission=0;state.shots=[];state.sparks=[];$('roundEvent').classList.remove('show');}
function resetAll(mode=state.mode){dirtyRender=true;state.mode=mode;state.external=false;state.native=false;state.dataset=null;state.selectedNeurons=[-1,-1];document.body.classList.remove('native');state.t=0;state.round=1;state.score=[0,0];state.tick=0;state.trace=[];obsClock=0;accumulator=0;agents=[agent(0),agent(1)];resetEpisode();syncLabels();log(mode==='learn'?'무지식 실험 시작 · 시야 + 직전 행동 / 끝 보상만 사용':'연출 모드 시작 · 규칙 기반 전투 / 합성 RNN 관측');}
function log(text){$('eventLog').textContent=`${state.t.toFixed(1).padStart(6,'0')}s  /  ${text}`;}
let toastTimer;function toast(text){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3200);}
function syncLabels(){let learning=state.mode==='learn',ext=state.external;document.querySelectorAll('.raster-label').forEach(e=>e.textContent=ext?'40 FRAMES · 32 UNITS':'40 SAMPLES · 32 UNITS');$('modeDescription').textContent=ext?`외부 시뮬레이션: ${state.dataset||'unnamed'} · 출처 미검증`:learning?'768유닛 합성 RNN · 자기 시야만 입력 · 승패 보상만 학습 · 성능 향상 미검증':'규칙 기반 전투 + 합성 신경 활동. 실제 초파리 학습 결과가 아닙니다.';$('sessionLabel').textContent=ext?'EXTERNAL MODEL STREAM':learning?'SPARSE-REWARD SELF-PLAY':'SHOWCASE SESSION';$('sourceLabel').textContent=ext?'외부 모델 스트림 · 사용자 제공':'합성 RNN · 실제 커넥톰 미연결';document.querySelector('.top-tag').textContent=ext?'외부 데이터 · 제공자 출처 선언 (미검증)':'시각화 프로토타입 · 실제 커넥톰 미연결';['A','B'].forEach((id,i)=>{$(`sub${id}`).textContent=`${ext?'EXTERNAL':'SYNTHETIC RNN'} · ${agents[i].brain.n} UNITS`;$(`policy${id}`).textContent=ext?'EXTERNAL / READ ONLY':learning?'REINFORCE / READOUT':'SCRIPTED / NO LEARNING';});$('resetBtn').disabled=ext;$('speed').disabled=ext&&!state.native;$('speedModeBtn').disabled=ext&&!state.native;$('mode').disabled=ext;
if(state.native){document.body.classList.add('native');$('mode').value='external';$('modeDescription').textContent='Python 병렬 PPO · 별도 관전 경기 · 합성 RNN / 실제 커넥톰 아님';$('sessionLabel').textContent='LIVE POLICY EXHIBITION · NOT A TRAINING ARENA';$('sourceLabel').textContent='정책이 계산한 활성 · 모식적 배치';document.querySelector('.top-tag').textContent='NATIVE TRAINER / HTML VIEWER';for(let id of ['A','B'])$(`policy${id}`).textContent='RECURRENT PPO / SYNTHETIC';$('trainPauseBtn').disabled=!!window.FLYFIGHT_NATIVE?.readOnly;$('saveModelBtn').disabled=!!window.FLYFIGHT_NATIVE?.readOnly;$('pixelToggle').disabled=false;}
else{$('trainPauseBtn').disabled=true;$('saveModelBtn').disabled=true;$('pixelToggle').disabled=true;}}
// Scene geometry: fly meshes are built from original primitives; no downloaded animal assets.
function add(type,parent,p,s,c,r=[0,0,0],kind=0){renderer.add(type,mul(parent,compose(p,s,r)),c,kind);}
function bone(parent,p,q,r,c){renderer.segment(transform(parent,p),transform(parent,q),r,c);}
function fly(a){let id=a.id,c=id===0?colors.a:colors.b,t=state.t,walk=a.moveSpeed,phase=a.phase;let root=mul(T(a.x,Math.sin(phase*2)*.04*walk,a.z),RY(a.yaw));let hit=a.hitFlash>0;
 add('sphere',I(),[a.x,.027,a.z],[.90,.012,1.22],color('#0b1a23',.44),[0,a.yaw,0]);
 add('ring',I(),[a.x,.039,a.z],[1.34,1,1.34],[...c.slice(0,3),.7],[0,0,0],2);
 let body=hit?color('#d5bd9b'):colors.tan;
 add('sphere',root,[0,1.42,-.88],[.51,.39,.86],colors.brown);
 for(let j=0;j<5;j++){let z=-.44-j*.245,sz=.49-(j*.048),cy=1.44-j*.025;add('sphere',root,[0,cy,z],[sz,.36-j*.025,.245],j%2===0?body:color('#624326'));}
 add('sphere',root,[0,1.29,-1.62],[.17,.19,.24],colors.dark);
 add('sphere',root,[0,1.59,-.01],[.49,.49,.64],hit?color('#d6bd9a'):color('#a2865b'));
 add('sphere',root,[0,1.85,.64],[.48,.43,.43],body);
 for(let side of [-1,1]){
  add('sphere',root,[side*.345,1.94,.85],[.30,.365,.305],colors.eye,[0,side*.2,0]);
  for(let k=0;k<20;k++){let yy=(k/19-.5)*.55,ang=k*2.39996,rr=Math.sqrt(Math.max(.01,1-(yy/.38)**2));let p=[side*(.35+.14*Math.cos(ang)*rr),1.94+yy,.90+.21*Math.sin(ang)*rr];add('small',root,p,[.038,.037,.04],k%3?color('#c85b3e'):color('#812c24'));}
  bone(root,[side*.13,2.16,.9],[side*.2,2.36,1.08],.032,colors.brown);add('small',root,[side*.2,2.36,1.08],[.065,.09,.065],colors.dark);
  bone(root,[side*.22,2.38,1.06],[side*.31,2.57,1.24],.009,colors.leg);
  for(let k=0;k<3;k++)bone(root,[side*(.24+k*.016),2.41+k*.04,1.1+k*.028],[side*(.37+k*.012),2.44+k*.043,1.11+k*.026],.005,colors.leg);
  // Front pair grips a fictional compact rifle. Middle and rear pairs walk.
  bone(root,[side*.37,1.58,.3],[side*.78,1.22,.81],.056,colors.leg);bone(root,[side*.78,1.22,.81],[side*.26,1.46,1.29],.046,colors.brown);add('small',root,[side*.26,1.46,1.29],[.08,.07,.10],colors.leg);
  for(let k=0;k<2;k++){let z=.10-k*.75,ph=phase+side*Math.PI/2+k*Math.PI,sw=Math.sin(ph)*.25*walk,lift=Math.max(0,Math.cos(ph))*.23*walk;let hip=[side*.37,1.39,z],knee=[side*(.94+.08*Math.sin(ph)),.80,z+.17+sw],foot=[side*1.16,.08+lift,z+.46-sw];bone(root,hip,knee,.057,colors.leg);bone(root,knee,foot,.039,colors.brown);bone(root,foot,[foot[0]+side*.14,.04+lift,foot[2]+.17],.025,colors.leg);add('small',root,knee,[.064,.064,.064],colors.leg);}
  let flap=.055*Math.sin(t*37+id),wingRoot=mul(root,mul(T(side*.28,1.94,-.27),mul(RY(-side*.31),GFX.RZ(side*(.07+flap)))));
  add('sphere',wingRoot,[side*.44,.02,-.74],[.52,.023,1.07],colors.wing,[.04,0,0]);
  const rootp=[0,.035,0];for(let k=0;k<5;k++){let q=[side*(.14+k*.16),.039,-.44-k*.20];bone(wingRoot,rootp,q,.008,color('#a8bbab',.7));bone(wingRoot,q,[side*(.30+k*.08),.041,-1.52+k*.09],.006,color('#95afa4',.6));}
 }
 for(let k=0;k<10;k++){let ang=k*.63,x=Math.cos(ang)*.34,z=Math.sin(ang)*.46;bone(root,[x,2.005,z],[x*1.13,2.11+(k%3)*.015,z*1.1],.007,colors.dark);}
 // Identification band, small side canister, and muzzle. Pitch is inherited by the whole weapon.
 add('box',root,[0,1.76,.22],[.63,.16,.20],[...c.slice(0,3),1]);
 let gun=mul(root,mul(T(.15,1.47,.95),RX(-a.pitch))),recoil=-a.muzzle*.16;
 add('box',gun,[0,0,.49+recoil],[.25,.24,.91],colors.gun);add('box',gun,[0,.15,.45+recoil],[.10,.10,.55],colors.steel);add('box',gun,[0,-.22,.34+recoil],[.13,.30,.19],colors.dark,[.18,0,0]);add('box',gun,[0,-.03,-.16+recoil],[.20,.22,.45],colors.dark);add('box',gun,[.132,0,.5+recoil],[.018,.071,.43],c,[0,0,0],2);bone(gun,[0,0,.90+recoil],[0,0,1.41+recoil],.059,colors.steel);bone(gun,[0,0,1.35+recoil],[0,0,1.54+recoil],.094,colors.dark);
 if(a.muzzle>.1){add('small',gun,[0,0,1.66],[.13*a.muzzle,.14*a.muzzle,.31],color('#fff2c4',.9),[0,0,0],2);add('small',gun,[0,0,1.9],[.05,.05,.15],c,[0,0,0],2);}
 if(a.hp<=0){/* Episode ends immediately; a short hit flash marks defeat without gore. */}
 return root;
}
function world(){renderer.reset();let ident=I(),w=mapSpec.width,d=mapSpec.depth;
 add('box',ident,[0,-.32,0],[w+1,.6,d+1],color('#344858'));
 add('box',ident,[0,-.025,0],[w,.08,d],color('#748791'),[0,0,0],1);
 add('box',ident,[0,-.67,0],[w+1.6,.12,d+1.6],color('#172735'));
 // Symmetric side routes and central crossing. Ground markings carry no rewards.
 for(let z of [-d*.29,0,d*.29])add('box',ident,[0,.024,z],[w-.8,.017,.12],color('#96b5bd',.42),[0,0,0],2);
 for(let x of [-w*.27,0,w*.27])add('box',ident,[x,.025,0],[.10,.018,d-.8],color('#b5c8c7',.3),[0,0,0],2);
 for(let z of [-d/2-.5,d/2+.5]){add('box',ident,[0,mapSpec.wall_height/2,z],[w+2,mapSpec.wall_height,1],color('#426274',.15));add('box',ident,[0,.24,z],[w+1,.32,.18],color('#294757'));add('box',ident,[0,mapSpec.wall_height,z],[w+1,.035,.07],color('#81c6d0'),[0,0,0],2);}
 for(let x of [-w/2-.5,w/2+.5]){add('box',ident,[x,mapSpec.wall_height/2,0],[1,mapSpec.wall_height,d+2],color('#426274',.15));add('box',ident,[x,.24,0],[.18,.32,d+1],color('#294757'));add('box',ident,[x,mapSpec.wall_height,0],[.07,.035,d+1],color('#81c6d0'),[0,0,0],2);}
 add('ring',ident,[0,.027,0],[6.6,1,6.6],color('#b0d1d4',.35));
 for(let [i,b]of obstacles.entries()){add('box',ident,[b.x,b.h/2,b.z],[b.w,b.h,b.d],color('#293e4d'));add('box',ident,[b.x,b.h+.025,b.z],[b.w,.05,b.d],color('#91a5af'));add('box',ident,[b.x,b.h*.64,b.z+b.d/2+.008],[b.w*.76,.075,.025],i%2?colors.b:colors.a,[0,0,0],2);for(let side of [-1,1])add('box',ident,[b.x+side*(b.w/2-.1),b.h*.48,b.z+b.d/2+.015],[.045,b.h*.68,.03],color('#506674'));}
 for(let a of agents)fly(a);
 for(let shot of state.shots){let col=shot.id===0?colors.a:colors.b;renderer.segment(shot.start,shot.end,.023,[...col.slice(0,3),clamp(shot.life/.15,0,1)],2);}
 for(let spark of state.sparks)add('small',ident,spark.p,[.035,.035,.035],[...spark.c.slice(0,3),clamp(spark.life*2,0,1)],[0,0,0],2);
 renderer.upload();
}
function pov(a){let eye=[a.x+Math.sin(a.yaw)*1.24,1.95,a.z+Math.cos(a.yaw)*1.24],d=[Math.sin(a.yaw)*Math.cos(a.pitch),Math.sin(a.pitch),Math.cos(a.yaw)*Math.cos(a.pitch)];return {eye,target:V.add(eye,d),fov:1.15};}
function mainCamera(){if(state.camera==='top')return {eye:[.01,Math.max(mapSpec.width,mapSpec.depth)*1.5,.1],target:[0,0,0],fov:.73};if(state.camera==='duel'){let x=(agents[0].x+agents[1].x)/2,z=(agents[0].z+agents[1].z)/2,d=clamp(Math.hypot(agents[0].x-agents[1].x,agents[0].z-agents[1].z)*.9+9,17,70);return {eye:[x+d*.65,d*.8,z+d*.75],target:[x,1,z],fov:.9};}if(state.camera.startsWith('follow')){let a=agents[state.camera==='followA'?0:1],d=[Math.sin(a.yaw),0,Math.cos(a.yaw)];return {eye:[a.x-d[0]*8,5.3,a.z-d[2]*8],target:[a.x+d[0]*3,1.2,a.z+d[2]*3],fov:.88};}let ce=Math.cos(state.elev),eye=[Math.sin(state.az)*state.dist*ce,Math.sin(state.elev)*state.dist,Math.cos(state.az)*state.dist*ce];return {eye,target:[0,.65,0],fov:.83};}
function collision(x,z){if(Math.abs(x)>mapSpec.width/2-.7||Math.abs(z)>mapSpec.depth/2-.7)return true;return obstacles.some(b=>Math.abs(x-b.x)<b.w/2+.62&&Math.abs(z-b.z)<b.d/2+.62);}
function move(a,dt){let [forward,strafe,turn,pitch]=a.action;a.yaw+=turn*1.25*dt;a.pitch=clamp(a.pitch+pitch*.5*dt,-.38,.38);let v=4.5,n=Math.max(1,Math.hypot(forward,strafe)),dx=(Math.sin(a.yaw)*forward+Math.cos(a.yaw)*strafe)*v*dt/n,dz=(Math.cos(a.yaw)*forward-Math.sin(a.yaw)*strafe)*v*dt/n;let before=[a.x,a.z];if(!collision(a.x+dx,a.z))a.x+=dx;if(!collision(a.x,a.z+dz))a.z+=dz;a.moveSpeed=clamp(Math.hypot(a.x-before[0],a.z-before[1])/dt/2.5,0,1);a.phase+=dt*(2+a.moveSpeed*10);a.muzzle=Math.max(0,a.muzzle-dt*12);a.hitFlash=Math.max(0,a.hitFlash-dt);}
function scripted(a,b){let dx=b.x-a.x,dz=b.z-a.z,dist=Math.hypot(dx,dz),target=Math.atan2(dx,dz),aim=target+Math.sin(state.t*2.7+a.id*1.1)*.078,turn=clamp(angleDiff(aim,a.yaw)*6,-1,1),error=Math.abs(angleDiff(target,a.yaw)),forward=dist>6.8?.85:dist<4.3?-.9:.12,strafe=a.strafe*.65;
 if(Math.floor(state.t/5+a.id)%2===0)strafe*=-1;
 if(collision(a.x+Math.sin(a.yaw)*.85,a.z+Math.cos(a.yaw)*.85)){forward=-.65;strafe=-strafe;}
 let blocked=rayBoxDistance([a.x,1.6,a.z],V.norm([dx,0,dz]),dist)<dist-.8;
 let fire=error<.17&&!blocked&&(Math.sin(state.t*1.4+a.id)>.0)?1:0;
 // Explicitly scripted showcase only. This function is never called in learning mode.
 return [forward,strafe,turn,clamp(-a.pitch*5,-1,1),fire];
}
function rayBoxDistance(o,d,maxD=40){let best=maxD;for(let b of obstacles){let mn=[b.x-b.w/2,0,b.z-b.d/2],mx=[b.x+b.w/2,b.h+.12,b.z+b.d/2],lo=0,hi=best;for(let k=0;k<3;k++){if(Math.abs(d[k])<1e-8){if(o[k]<mn[k]||o[k]>mx[k]){hi=-1;break;}}else{let t1=(mn[k]-o[k])/d[k],t2=(mx[k]-o[k])/d[k];if(t1>t2)[t1,t2]=[t2,t1];lo=Math.max(lo,t1);hi=Math.min(hi,t2);}}if(hi>=lo&&hi>0)best=Math.min(best,lo);}return best;}
function raySphereDistance(o,d,center,radius,maxD){let oc=V.sub(o,center),b=V.dot(oc,d),c=V.dot(oc,oc)-radius*radius,disc=b*b-c;if(disc<0)return maxD;let t=-b-Math.sqrt(disc);return t>0&&t<maxD?t:maxD;}
function fire(a,b){if(a.action[4]<.5||state.t-a.lastShot<.34||a.hp<=0)return 0;a.lastShot=state.t;a.shots++;a.muzzle=1;let cam=pov(a),o=cam.eye,d=V.norm(V.sub(cam.target,o)),wallD=rayBoxDistance(o,d,24),bodyD=raySphereDistance(o,d,[b.x,1.45,b.z],.72,wallD),headD=raySphereDistance(o,d,[b.x,2.30,b.z],.34,wallD),headshot=headD<bodyD&&headD<wallD,hit=headshot||bodyD<wallD,maxD=headshot?headD:hit?bodyD:wallD;
 let end=V.add(o,V.mul(d,maxD)),root=mul(T(a.x,0,a.z),RY(a.yaw)),gun=mul(root,mul(T(.15,1.47,.95),RX(-a.pitch))),start=transform(gun,[0,0,1.6]);state.shots.push({id:a.id,start,end,life:.10,headshot});
 if(hit){a.hits++;if(headshot)a.headshots++;b.hitFlash=.16;for(let i=0;i<(headshot?13:7);i++)state.sparks.push({p:end.slice(),v:[(rngScene()-.5)*3,rngScene()*2,(rngScene()-.5)*3],life:.28,c:headshot?color('#fff0a8'):a.id===0?colors.a:colors.b});log(`FLY ${a.id===0?'A':'B'} → ${headshot?'HEADSHOT · 100 피해':'명중 · 34 피해'}${state.mode==='learn'?'':' · 보상 없음'}`);}
 return headshot?100:hit?34:0;
}
function finishRound(winner){if(state.intermission>0)return;state.intermission=2.8;let rewards=winner<0?[0,0]:winner===0?[1,-1]:[-1,1];if(winner>=0)state.score[winner]++;if(state.mode==='learn')agents.forEach((a,i)=>a.brain.reward(rewards[i]));
 let label=winner<0?'DRAW':`FLY ${winner===0?'A':'B'} WINS`;$('roundResult').textContent=label;$('roundResult').style.color=winner===0?'#67e6ee':winner===1?'#f4bb79':'#d2e3ed';$('roundReward').textContent=state.mode==='learn'?`A: ${rewards[0]>0?'+':''}${rewards[0]} / B: ${rewards[1]>0?'+':''}${rewards[1]}  ·  출력층 갱신 ${winner>=0?'적용':'없음'}`:'연출 모드 · 학습하지 않음';$('roundEvent').classList.add('show');state.trace.push({round:state.round,t:state.t,winner,rewards,mode:state.mode});log(`${label} · 다음 라운드 자동 시작`);}
function decide(){world();let observations=agents.map(a=>renderer.observe(pov(a)));agents.forEach((a,i)=>{a.brain.step(observations[i],a.action);if(state.mode==='learn')a.action=a.brain.policy();});}
function simulationStep(dt){state.t+=dt;state.tick++;if(state.intermission>0){state.intermission-=dt;for(let s of state.shots)s.life-=dt;state.shots=state.shots.filter(s=>s.life>0);for(let p of state.sparks)p.life-=dt;state.sparks=state.sparks.filter(s=>s.life>0);for(let a of agents){a.muzzle=Math.max(0,a.muzzle-dt*12);a.hitFlash=Math.max(0,a.hitFlash-dt);a.moveSpeed*=.90;}if(state.intermission<=0){state.round++;resetEpisode();obsClock=0;}return;}
 state.roundTime+=dt;obsClock+=dt;
 if(state.mode==='showcase')agents.forEach((a,i)=>a.action=scripted(a,agents[1-i]));
 if(obsClock>=.2){obsClock-=.2;decide();}
 agents.forEach(a=>move(a,dt));let damageB=fire(agents[0],agents[1]),damageA=fire(agents[1],agents[0]);agents[0].hp=Math.max(0,agents[0].hp-damageA);agents[1].hp=Math.max(0,agents[1].hp-damageB);
 for(let s of state.shots)s.life-=dt;state.shots=state.shots.filter(s=>s.life>0);for(let p of state.sparks){p.life-=dt;p.p=p.p.map((v,i)=>v+p.v[i]*dt);p.v[1]-=5*dt;}state.sparks=state.sparks.filter(s=>s.life>0);
 if(agents[0].hp<=0||agents[1].hp<=0)finishRound(agents[0].hp<=0&&agents[1].hp<=0?-1:agents[0].hp<=0?1:0);else if(state.roundTime>=state.duration)finishRound(-1);
}
function isVisible(r){return r.bottom>0&&r.top<innerHeight&&r.right>0&&r.left<innerWidth&&r.width>0&&r.height>0;}
function render(){renderer.resize();let gl=renderer.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.disable(gl.SCISSOR_TEST);gl.viewport(0,0,$('gl').width,$('gl').height);renderer.clear([.028,.044,.063,1]);world();let cam=mainCamera(),ar=$('arena').getBoundingClientRect();if(isVisible(ar)){renderer.viewport(ar);renderer.drawWorld(cam,ar.width/ar.height);}for(let i=0;i<2;i++){let id=i===0?'A':'B',pr=$(`pov${id}`).getBoundingClientRect();if(isVisible(pr)&&(!state.native||!state.showPixels)){renderer.viewport(pr);renderer.clear([.025,.042,.059,1]);let w=Math.min(pr.width,pr.height*20/12),h=w*12/20,left=pr.left+(pr.width-w)/2,top=pr.top+(pr.height-h)/2;renderer.viewport({left,top,right:left+w,bottom:top+h,width:w,height:h});renderer.drawWorld(pov(agents[i]),20/12);}let nr=$(`brain${id}`).getBoundingClientRect();if(isVisible(nr))lastNeuralMatrices[i]=renderer.drawNeural(agents[i].brain,nr,state.brainAngles[i],state.selectedNeurons[i],{zoom:state.brainZoom[i],edges:state.brainEdges[i],pointScale:state.brainPointScale[i]});}
 let vp=mul(perspective(cam.fov,ar.width/ar.height),lookAt(cam.eye,cam.target));for(let i=0;i<2;i++){let a=agents[i],p=[a.x,3.0,a.z,1],q=[0,0,0,0];for(let row=0;row<4;row++)for(let k=0;k<4;k++)q[row]+=vp[k*4+row]*p[k];let el=$(i?'nameB':'nameA');if(q[3]>0&&Math.abs(q[0]/q[3])<1&&Math.abs(q[1]/q[3])<1){el.style.display='block';el.style.left=`${(q[0]/q[3]*.5+.5)*ar.width}px`;el.style.top=`${(-q[1]/q[3]*.5+.5)*ar.height}px`;}else el.style.display='none';}
 gl.disable(gl.SCISSOR_TEST);
}
function raster(canvas,brain){let d=Math.min(devicePixelRatio||1,1.5),w=Math.round(canvas.clientWidth*d),h=Math.round(canvas.clientHeight*d);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}let ctx=canvas.getContext('2d');ctx.fillStyle='#09131d';ctx.fillRect(0,0,w,h);let hist=brain.history,cols=40,rows=32;for(let j=0;j<hist.length;j++)for(let k=0;k<rows;k++){let a=hist[j][k],r=brain.region[Math.floor(k*brain.n/rows)]||0,c=palette[r%5];ctx.fillStyle=`rgba(${Math.floor(c[0]*255)},${Math.floor(c[1]*255)},${Math.floor(c[2]*255)},${clamp(a*.97,.015,1)})`;ctx.fillRect((cols-hist.length+j)*w/cols,k*h/rows,Math.max(1,w/cols-.7),Math.max(1,h/rows-.4));}ctx.fillStyle='#7695a96b';for(let j=10;j<40;j+=10)ctx.fillRect(w*j/40,0,.5,h);}
function neuralValue(brain,index){let signed=brain.signedActivity&&Number.isFinite(brain.signedActivity[index])?brain.signedActivity[index]:null,magnitude=brain.activity[index]||0;return {signed,magnitude};}
function updateNeuralProbe(i){let id=i?'B':'A',index=state.selectedNeurons[i],el=$(`neuralProbe${id}`),brain=agents[i].brain;if(!el)return;if(index<0||index>=brain.n){el.innerHTML='뉴런을 클릭하면 <b>hidden 값</b>을 고정 표시';return;}let v=neuralValue(brain,index),signed=v.signed===null?'미제공':v.signed.toFixed(5);el.innerHTML=`<b>${brain.ids[index]}</b> · hidden ${signed} · |h| ${v.magnitude.toFixed(5)}`;}
for(let id of ['A','B']){$(`bars${id}`).innerHTML=['이동','옆걸음','회전','시점','발사'].map((label,j)=>`<div class="bar-row"><span>${label}</span><div class="track"><div id="bar${id}${j}" class="fill"></div></div><output id="val${id}${j}">0.0</output></div>`).join('');}
function updateUI(){for(let [i,id]of ['A','B'].entries()){let a=agents[i],b=a.brain;$(`active${id}`).innerHTML=`${b.active.toLocaleString()} <small>/ ${b.n.toLocaleString()}</small>`;$(`mean${id}`).innerHTML=`${b.mean.toFixed(2)} <small>/ 1</small>`;$(`health${id}`).style.width=`${a.hp}%`;$(`score${id}`).textContent=String(state.score[i]).padStart(2,'0');$(`update${id}`).textContent=state.native?`v${state.policyVersion}`:state.mode==='learn'?`ΔW ${b.updates}`:'ΔW —';for(let j=0;j<5;j++){let v=a.action[j]||0;$(`bar${id}${j}`).style.width=`${Math.abs(v)*100}%`;$(`val${id}${j}`).textContent=j===4?(v>.5?'ON':'OFF'):v.toFixed(3);}$(`action${id}`).textContent=a.action[4]>.5?'FIRE':Math.abs(a.action[2])>.2?'TURN':Math.hypot(a.action[0],a.action[1])>.1?'MOVE':'OBSERVE';raster($(`raster${id}`),b);updateNeuralProbe(i);}
 if(state.native){let m=state.training;$('trainDevice').textContent=String(m.device||'—').toUpperCase();$('trainEnvs').textContent=Number(m.envs||0).toLocaleString();$('trainSteps').textContent=Number(m.env_steps||0).toLocaleString();$('trainSps').textContent=Number.isFinite(m.env_steps_s)?Math.round(m.env_steps_s).toLocaleString():'—';$('trainVersion').textContent=String(m.update||0);$('trainDraws').textContent=Number.isFinite(m.draw_rate)?`${(m.draw_rate*100).toFixed(1)}%`:'—';$('trainPauseBtn').textContent=m.train_paused?'학습 재개':'학습 일시정지';$('nativeStatus').textContent=m.error?`오류: ${m.error}`:m.train_paused?'학습 일시정지 · 관전 별도':m.state==='stopped'?'학습 종료 · 마지막 정책 관전':'학습 진행 · 관전과 독립';}
 $('roundLabel').textContent=`ROUND ${String(state.round).padStart(2,'0')}`;$('clockLabel').textContent=`${String(Math.floor(state.roundTime/60)).padStart(2,'0')}:${String(Math.floor(state.roundTime%60)).padStart(2,'0')}`;$('timeLabel').textContent=`${state.roundTime.toFixed(1)} / ${state.duration.toFixed(1)} s`;$('progress').style.width=`${clamp(state.roundTime/state.duration*100,0,100)}%`;$('tickValue').textContent=state.tick.toLocaleString();$('fpsValue').textContent=state.fps?String(Math.round(state.fps)):'—';$('runStatus').textContent=state.paused?'PAUSED':state.external?'EXTERNAL':'RUNNING';}
function setPaused(p){dirtyRender=true;state.paused=p;accumulator=0;$('pauseBtn').textContent=p?'▶':'Ⅱ';$('pauseBtn').setAttribute('aria-label',p?'재생':'일시정지');if(!p&&pendingFrame){applyFrame(pendingFrame);pendingFrame=null;}updateUI();}
const SPEEDS=[.5,1,2,4,8],FAST_SPEED=4;
function updateSpeedUI(){let fast=state.speed>1;$('speed').value=String(state.speed);$('speedModeBtn').textContent=fast?`≫ ${state.speed}×`:'≫ 배속';$('speedModeBtn').classList.toggle('active',fast);$('speedModeBtn').setAttribute('aria-pressed',String(fast));}
function setSpeed(value,announce=false){let speed=Number(value);if(!SPEEDS.includes(speed))return false;state.speed=speed;accumulator=0;updateSpeedUI();if(state.native)command('view_speed',speed);if(announce)toast(speed===1?'배속 모드 해제 · 1×':`배속 모드 · ${speed}×`);return true;}
$('pauseBtn').onclick=()=>{if(state.native)command(state.paused?'view_resume':'view_pause');setPaused(!state.paused);};$('resetBtn').onclick=()=>{resetAll();toast('신경망 가중치·활동·점수를 초기화했습니다.');};$('speed').onchange=e=>setSpeed(e.target.value,true);$('speedModeBtn').onclick=()=>setSpeed(state.speed===1?FAST_SPEED:1,true);$('mode').onchange=e=>{resetAll(e.target.value);setPaused(false);toast(state.mode==='learn'?'무지식 초기 정책으로 시작합니다. 초기에는 전투를 잘하지 못할 수 있습니다.':'규칙 기반 전투 관전으로 전환했습니다.');};
$('infoBtn').onclick=()=>$('info').showModal();$('closeInfo').onclick=()=>$('info').close();$('connectBtn').onclick=()=>$('connect').showModal();$('closeConnect').onclick=()=>$('connect').close();
for(let d of document.querySelectorAll('dialog'))d.addEventListener('click',e=>{if(e.target===d){let r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
for(let b of document.querySelectorAll('[data-camera]'))b.onclick=()=>{dirtyRender=true;state.camera=b.dataset.camera;document.querySelectorAll('[data-camera]').forEach(x=>x.classList.toggle('active',x===b));};$('autoOrbit').onclick=()=>{state.auto=!state.auto;$('autoOrbit').classList.toggle('active',state.auto);};
const edgeLabels={active:'연결:활성',all:'연결:전체',off:'연결:숨김'},pointScales=[1,1.38,.72],pointLabels=['점:M','점:L','점:S'];
for(let i=0;i<2;i++){let id=i?'B':'A',view=$(`brain${id}`),tools=document.createElement('div');tools.className='neural-tools';tools.innerHTML=`<button id="neuralEdges${id}" class="active" title="연결선: 활성/전체/숨김">연결:활성</button><button id="neuralSize${id}" title="뉴런 점 크기">점:M</button><button id="neuralZoomOut${id}" title="축소">−</button><button id="neuralZoomIn${id}" title="확대">＋</button>`;let probe=document.createElement('div');probe.id=`neuralProbe${id}`;probe.className='neural-probe';view.append(tools,probe);$(`neuralEdges${id}`).onclick=()=>{let order=['active','all','off'],next=order[(order.indexOf(state.brainEdges[i])+1)%order.length];state.brainEdges[i]=next;$(`neuralEdges${id}`).textContent=edgeLabels[next];$(`neuralEdges${id}`).classList.toggle('active',next!=='off');dirtyRender=true;};$(`neuralSize${id}`).onclick=()=>{let current=pointScales.indexOf(state.brainPointScale[i]),next=(current+1)%pointScales.length;state.brainPointScale[i]=pointScales[next];$(`neuralSize${id}`).textContent=pointLabels[next];dirtyRender=true;};$(`neuralZoomOut${id}`).onclick=()=>{state.brainZoom[i]=clamp(state.brainZoom[i]-.18,.7,2.2);dirtyRender=true;};$(`neuralZoomIn${id}`).onclick=()=>{state.brainZoom[i]=clamp(state.brainZoom[i]+.18,.7,2.2);dirtyRender=true;};view.addEventListener('wheel',e=>{e.preventDefault();state.brainZoom[i]=clamp(state.brainZoom[i]-Math.sign(e.deltaY)*.12,.7,2.2);dirtyRender=true;},{passive:false});}
function nearestNeuron(i,e){let el=$(i?'brainB':'brainA'),mat=lastNeuralMatrices[i];if(!mat)return -1;let r=el.getBoundingClientRect(),b=agents[i].brain,m=mat.vp,nearest=-1,dist=100;for(let j=0;j<b.n;j++){let p=b.pos[j],x=m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],y=m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],w=m[3]*p[0]+m[7]*p[1]+m[11]*p[2]+m[15];if(w<=0)continue;let sx=r.left+(x/w*.5+.5)*r.width,sy=r.top+(-y/w*.5+.5)*r.height,d=(e.clientX-sx)**2+(e.clientY-sy)**2;if(d<dist){dist=d;nearest=j;}}return nearest;}
let drag=null;function bindDrag(el,kind){el.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag={kind,x:e.clientX,y:e.clientY,startX:e.clientX,startY:e.clientY,moved:false,pointerId:e.pointerId};el.setPointerCapture(e.pointerId);});el.addEventListener('pointermove',e=>{if(!drag||drag.kind!==kind)return;dirtyRender=true;let dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)>4)drag.moved=true;if(kind==='arena'){state.az-=dx*.006;state.elev=clamp(state.elev+dy*.005,.13,1.48);state.camera='orbit';document.querySelectorAll('[data-camera]').forEach(b=>b.classList.toggle('active',b.dataset.camera==='orbit'));}else state.brainAngles[kind]+=dx*.012;drag.x=e.clientX;drag.y=e.clientY;});el.addEventListener('pointerup',e=>{if(drag&&drag.kind!=='arena'&&!drag.moved){let nearest=nearestNeuron(drag.kind,e);state.selectedNeurons[drag.kind]=nearest;updateNeuralProbe(drag.kind);dirtyRender=true;}drag=null;});el.addEventListener('pointercancel',()=>drag=null);}
bindDrag($('arena'),'arena');bindDrag($('brainA'),0);bindDrag($('brainB'),1);$('arena').addEventListener('wheel',e=>{e.preventDefault();dirtyRender=true;state.dist=clamp(state.dist+e.deltaY*.03,7,130);},{passive:false});
addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName)||document.querySelector('dialog[open]'))return;if(e.code==='Space'){e.preventDefault();if(state.native)command(state.paused?'view_resume':'view_pause');setPaused(!state.paused);}else if(e.code==='KeyB'){e.preventDefault();setSpeed(state.speed===1?FAST_SPEED:1,true);}});
for(let i=0;i<2;i++){let el=$(i?'brainB':'brainA');el.addEventListener('pointermove',e=>{if(drag||e.target.closest('button')){$('tooltip').style.display='none';return;}let b=agents[i].brain,nearest=nearestNeuron(i,e);if(nearest>=0){let tip=$('tooltip'),v=neuralValue(b,nearest),signed=v.signed===null?'미제공':v.signed.toFixed(5);tip.textContent=`${i?'B':'A'} · ${b.ids[nearest]}\nhidden ${signed}\n|hidden| ${v.magnitude.toFixed(5)} / 1\n클릭해서 고정 · 모식 좌표`;tip.style.whiteSpace='pre';tip.style.display='block';tip.style.left=`${clamp(e.clientX+14,8,innerWidth-220)}px`;tip.style.top=`${Math.min(e.clientY+12,innerHeight-125)}px`;}else $('tooltip').style.display='none';});el.addEventListener('pointerleave',()=>$('tooltip').style.display='none');}
$('captureBtn').onclick=()=>{render();let r=$('arena').getBoundingClientRect(),d=renderer.dpr,c=document.createElement('canvas');c.width=Math.round(r.width*d);c.height=Math.round(r.height*d)+92;let ctx=c.getContext('2d');ctx.fillStyle='#0a1420';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage($('gl'),r.left*d,r.top*d,r.width*d,r.height*d,0,0,c.width,c.height-92);ctx.fillStyle='#e6f1f6';ctx.font='bold 20px sans-serif';ctx.fillText(`FLYFIGHT ZERO    A ${state.score[0]} : ${state.score[1]} B`,20,c.height-57);ctx.fillStyle='#b4c7d6';ctx.font='12px sans-serif';ctx.fillText(`${state.external?'External stream (unverified)':state.mode==='learn'?'Synthetic RNN / sparse-reward experiment':'Scripted combat / synthetic neural state'} · t = ${state.t.toFixed(2)} s`,20,c.height-33);ctx.fillStyle='#d0b888';ctx.fillText('Visualization prototype. No real fly connectome included.',20,c.height-13);c.toBlob(blob=>{if(!blob){toast('장면 저장에 실패했습니다.');return;}let url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`FlyFight_scene_${Math.floor(state.t)}s.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);},'image/png');};
// External stream contract: hello defines neuron IDs/layout; frame updates both agents atomically.
// It never sends data back and never evaluates code supplied by the socket.
function validatePixels(o){if(!Number.isInteger(o.width)||!Number.isInteger(o.height)||o.width<1||o.width>128||o.height<1||o.height>96||typeof o.rgb_base64!=='string'||o.rgb_base64.length>50000)throw Error('잘못된 RGB 입력');let raw;try{raw=atob(o.rgb_base64);}catch(e){throw Error('잘못된 RGB base64');}if(raw.length!==o.width*o.height*3)throw Error('RGB 길이 불일치');}
function drawPixels(i,o){let raw=atob(o.rgb_base64),c=$(i?'pixelsB':'pixelsA');c.width=o.width;c.height=o.height;let ctx=c.getContext('2d'),data=ctx.createImageData(o.width,o.height);for(let k=0;k<o.width*o.height;k++){for(let j=0;j<3;j++)data.data[k*4+j]=raw.charCodeAt(k*3+j);data.data[k*4+3]=255;}ctx.putImageData(data,0,0);$(`pixelMeta${i?'B':'A'}`).textContent=state.showPixels?`실제 입력 ${o.width} × ${o.height} RGB`:'상세 3D 재구성 · 학습 입력과 다름';}
function command(name,value){if(socket&&socket.readyState===WebSocket.OPEN&&state.native)socket.send(JSON.stringify({type:'command',command:name,value}));}
function finiteArray(a,n){return Array.isArray(a)&&a.length===n&&a.every(Number.isFinite);}
function installExternal(meta){if(meta.version!==1||!Array.isArray(meta.neurons)||meta.neurons.length<1||meta.neurons.length>4096)throw Error('hello: version 1, 1~4096개 표시 유닛이 필요합니다.');let ids=new Set();for(let n of meta.neurons){if(typeof n.id!=='string'||n.id.length>120||ids.has(n.id)||![n.x,n.y,n.z].every(Number.isFinite))throw Error('hello: 유닛 ID·좌표가 올바르지 않습니다.');ids.add(n.id);}if(typeof meta.dataset!=='string'||meta.dataset.length>180)throw Error('hello: dataset 문자열이 필요합니다.');if(!['simulation','recorded','synthetic'].includes(meta.activity_source))throw Error('hello: activity_source를 simulation / recorded / synthetic 중 지정해 주세요.');
 let points=meta.neurons.map(n=>[n.x,n.y,n.z]),mins=[0,1,2].map(k=>Math.min(...points.map(p=>p[k]))),maxs=[0,1,2].map(k=>Math.max(...points.map(p=>p[k]))),center=mins.map((v,k)=>(v+maxs[k])/2),span=Math.max(...mins.map((v,k)=>maxs[k]-v),1e-6),positions=points.map(p=>p.map((v,k)=>(v-center[k])/span*4.4));
 let edges=Array.isArray(meta.edges)?meta.edges:[];if(edges.length>12000||edges.some(e=>!finiteArray(e,2)||e.some(i=>!Number.isInteger(i)||i<0||i>=points.length)))throw Error('hello: 연결 인덱스가 올바르지 않습니다.');
 for(let a of agents){let b=a.brain;b.n=points.length;b.pos=positions.map(p=>p.slice());b.ids=meta.neurons.map(n=>n.id);b.region=meta.neurons.map(n=>Number.isInteger(n.group)?clamp(n.group,0,4):2);b.activity=new Float32Array(b.n);b.signedActivity=null;b.history=[];b.displayEdges=edges.slice();b.stats();a.action=[0,0,0,0,0];a.hp=100;}state.selectedNeurons=[-1,-1];
 if(meta.map)setMap(meta.map);state.native=meta.native===true;state.external=true;state.mode='external';state.dataset=meta.dataset;state.shots=[];state.sparks=[];state.intermission=0;state.duration=Number.isFinite(meta.round_duration)&&meta.round_duration>0?meta.round_duration:60;lastExternalT=-Infinity;externalHello=true;$('roundEvent').classList.remove('show');syncLabels();$('connectionStatus').textContent=`수신 준비 · ${meta.dataset} / ${points.length} 표시 유닛 / ${meta.activity_source} (제공자 선언)`;log('외부 스트림 연결 · 내장 정책·학습 중지');setPaused(false);
}
function applyFrame(f){if(!externalHello)throw Error('frame 전에 hello를 보내야 합니다.');if(!Number.isFinite(f.t)||f.t<lastExternalT)throw Error('frame.t는 이전 시각 이상인 유한수여야 합니다.');if(!Array.isArray(f.agents)||f.agents.length!==2)throw Error('A/B 두 개체 프레임이 필요합니다.');let ordered=['A','B'].map(id=>f.agents.find(a=>a.id===id));for(let [i,a]of ordered.entries()){if(!a||!finiteArray(a.position,2)||!Number.isFinite(a.yaw)||!Number.isFinite(a.hp)||!finiteArray(a.activity,agents[i].brain.n)||!finiteArray(a.action,5))throw Error('개체 position/yaw/hp/activity/action 형식을 확인해 주세요.');if(a.signed_activity!==undefined&&(!finiteArray(a.signed_activity,agents[i].brain.n)||a.signed_activity.some(v=>v< -1||v>1)))throw Error('signed_activity는 유닛 수와 같은 -1~1 배열이어야 합니다.');if(a.position.some(v=>Math.abs(v)>1000)||a.activity.some(v=>v<0||v>1))throw Error('활성은 0~1, 위치는 ±1000 이내여야 합니다.');}if(f.score!==undefined&&(!finiteArray(f.score,2)||f.score.some(x=>x<0)))throw Error('score는 0 이상인 숫자 2개여야 합니다.');if(f.agents)for(let a of f.agents)if(a.observation)validatePixels(a.observation);if(f.events&&(!Array.isArray(f.events)||f.events.length>100))throw Error('events는 최대 100개 배열입니다.');
 let dt=lastExternalT===-Infinity?0:Math.max(0,f.t-lastExternalT);for(let [i,src]of ordered.entries()){let a=agents[i],dx=src.position[0]-a.x,dz=src.position[1]-a.z;a.moveSpeed=dt>0?clamp(Math.hypot(dx,dz)/dt/2.8,0,1):0;a.phase+=dt*(2+10*a.moveSpeed);a.x=src.position[0];a.z=src.position[1];a.yaw=src.yaw;a.pitch=Number.isFinite(src.pitch)?clamp(src.pitch,-1.5,1.5):0;a.hp=clamp(src.hp,0,100);a.action=src.action.map(v=>clamp(v,-1,1));a.brain.activity.set(src.activity);if(src.signed_activity!==undefined){if(!a.brain.signedActivity||a.brain.signedActivity.length!==a.brain.n)a.brain.signedActivity=new Float32Array(a.brain.n);a.brain.signedActivity.set(src.signed_activity);}else a.brain.signedActivity=null;a.brain.stats();a.brain.history.push(Array.from({length:32},(_,j)=>a.brain.activity[Math.floor(j*a.brain.n/32)]));if(a.brain.history.length>40)a.brain.history.shift();a.muzzle=Math.max(0,a.muzzle-dt*12);}
 state.shots=state.shots.map(s=>({...s,life:s.life-dt})).filter(s=>s.life>0);for(let e of f.events||[]){if(e.type==='shot'&&['A','B'].includes(e.agent)&&finiteArray(e.start,3)&&finiteArray(e.end,3)){let id=e.agent==='A'?0:1,headshot=e.headshot===true;state.shots.push({id,start:e.start,end:e.end,life:.18,headshot});agents[id].muzzle=1;if(e.hit===true)agents[id].hits++;if(headshot){agents[id].headshots++;log(`FLY ${e.agent} → HEADSHOT · 100 피해`);}}}
 if(Number.isInteger(f.policy_version))state.policyVersion=f.policy_version;
if(f.training&&typeof f.training==='object')state.training=f.training;
if(state.native){for(let [i,a]of ordered.entries())if(a.observation)drawPixels(i,a.observation);$('inputTime').textContent=`입력 t=${Number.isFinite(f.input_t)?f.input_t.toFixed(1):'—'}s · 물리 t=${f.t.toFixed(1)}s`;if(f.result){$('roundResult').textContent=f.result==='DRAW'?'DRAW':`FLY ${f.result} WINS`;$('roundReward').textContent='별도 관전 경기 · 이 경험은 학습에 넣지 않음';$('roundEvent').classList.add('show');}else if(!f.intermission)$('roundEvent').classList.remove('show');}
state.t=f.t;lastExternalT=f.t;state.round=Number.isInteger(f.round)&&f.round>0?f.round:1;state.roundTime=Number.isFinite(f.round_time)?Math.max(0,f.round_time):f.t%state.duration;if(f.score)state.score=f.score.slice();state.tick++;dirtyRender=true;}
function ingest(message){if(message.type==='ack'){if(message.train_paused!==undefined)state.training.train_paused=message.train_paused;toast('명령 수신: '+message.command);return;}if(message.type==='error'){toast(message.message||'서버 오류');return;}if(message.type==='hello')installExternal(message);else if(message.type==='frame'){if(state.paused){pendingFrame=message;return;}applyFrame(message);}else throw Error('지원 메시지: hello / frame');}
function disconnect(){if(socket){socket.onclose=null;socket.close();socket=null;}externalHello=false;lastExternalT=-Infinity;pendingFrame=null;$('connectionStatus').textContent='연결 안 됨';state.duration=60;$('mode').value='showcase';resetAll('showcase');setPaused(false);}
$('startConnect').onclick=()=>{let url=$('wsUrl').value.trim();try{let u=new URL(url);if(!['ws:','wss:'].includes(u.protocol))throw Error('ws:// 또는 wss:// 주소가 필요합니다.');if(socket){socket.onclose=null;socket.close();}externalHello=false;socket=new WebSocket(url);$('connectionStatus').textContent='연결 중…';socket.onopen=()=>{setPaused(true);$('connectionStatus').textContent='연결됨 · 학습 백엔드 초기화 / hello 대기';};socket.onmessage=e=>{try{if(typeof e.data!=='string'||e.data.length>4_000_000)throw Error('최대 4MB 텍스트 JSON만 지원합니다.');ingest(JSON.parse(e.data));}catch(err){$('connectionStatus').textContent=`메시지 거부: ${err.message}`;}};socket.onerror=()=>{$('connectionStatus').textContent='연결 실패 · 로컬 서버 주소·실행 여부를 확인해 주세요.';};socket.onclose=()=>{socket=null;externalHello=false;$('connectionStatus').textContent='연결 종료 · 마지막 프레임 유지';setPaused(true);toast('외부 모델 연결이 종료되었습니다. 마지막 상태에서 멈춥니다.');};}catch(e){$('connectionStatus').textContent=e.message;}};
$('disconnectBtn').onclick=()=>{disconnect();toast('외부 연결을 해제하고 연출 모드로 전환했습니다.');};
// Minimal public integration and validation hooks, without remote code execution.
const publicState=()=>({coordinateSystem:'ground plane x/z; +y is up',map:{width:mapSpec.width,depth:mapSpec.depth,obstacles:obstacles.length},native:state.native,policyVersion:state.policyVersion,training:state.training,mode:state.mode,t:state.t,round:state.round,roundTime:state.roundTime,score:state.score.slice(),paused:state.paused,speed:state.speed,fps:state.fps,renderScale:state.renderScale,external:state.external,neuralView:{zoom:state.brainZoom.slice(),edges:state.brainEdges.slice(),pointScale:state.brainPointScale.slice(),selected:state.selectedNeurons.map((index,i)=>index>=0?{index,id:agents[i].brain.ids[index],magnitude:agents[i].brain.activity[index],signed:agents[i].brain.signedActivity?agents[i].brain.signedActivity[index]:null}:null)},agents:agents.map(a=>({id:a.id===0?'A':'B',position:[a.x,a.z],yaw:a.yaw,hp:a.hp,actions:a.action.slice(),mean:a.brain.mean,units:a.brain.n,updates:a.brain.updates,shots:a.shots,hits:a.hits,headshots:a.headshots})),completedRounds:state.trace.slice()});
window.FlyFight={version:'0.2.0',ingest,disconnect,getState:publicState,getNeuralSample:(i=0)=>({ids:agents[i].brain.ids.slice(0,10),activity:Array.from(agents[i].brain.activity.slice(0,10)),signedActivity:agents[i].brain.signedActivity?Array.from(agents[i].brain.signedActivity.slice(0,10)):null}),setPaused,setSpeed};
window.render_game_to_text=()=>JSON.stringify(publicState());
window.advanceTime=ms=>{if(state.external)return;if(!Number.isFinite(ms)||ms<0)throw Error('advanceTime(ms)는 0 이상의 유한수가 필요합니다.');let steps=Math.max(1,Math.round(ms/(1000/30)));for(let i=0;i<steps;i++)simulationStep(1/30);render();updateUI();};
$('trainPauseBtn').onclick=()=>command(state.training.train_paused?'train_resume':'train_pause');
$('saveModelBtn').onclick=()=>{command('checkpoint');toast('현재 업데이트가 끝나면 latest.pt를 저장합니다.');};
$('pixelToggle').onclick=()=>{state.showPixels=!state.showPixels;document.body.classList.toggle('pretty-pov',!state.showPixels);$('pixelToggle').textContent=state.showPixels?'시야: 실제 입력':'시야: 상세 3D';for(let id of ['A','B'])$(`pixelMeta${id}`).textContent=state.showPixels?'실제 정책 RGB 입력':'상세 3D 재구성 · 학습 입력과 다름';dirtyRender=true;};
resetAll('showcase');updateSpeedUI();
if(window.FLYFIGHT_NATIVE){setPaused(true);$('modeDescription').textContent='Python 학습 서버 연결 중 · 연출 봇은 정지됨';$('wsUrl').value=`${location.protocol==='https:'?'wss':'ws'}://${location.host}${window.FLYFIGHT_NATIVE.wsPath}?token=${encodeURIComponent(window.FLYFIGHT_NATIVE.token)}`;setTimeout(()=>$('startConnect').click(),100);}
let fpsFrames=0,fpsSince=performance.now(),lastDraw=0,lowFpsSamples=0,highFpsSamples=0;
function tuneRenderScale(){if(state.fps<48){lowFpsSamples++;highFpsSamples=0;}else if(state.fps>57){highFpsSamples++;lowFpsSamples=0;}else{lowFpsSamples=0;highFpsSamples=0;}if(lowFpsSamples>=2&&state.renderScale>.65){state.renderScale=Math.max(.65,state.renderScale-.15);renderer.setRenderScale(state.renderScale);lowFpsSamples=0;dirtyRender=true;}else if(highFpsSamples>=4&&state.renderScale<1){state.renderScale=Math.min(1,state.renderScale+.1);renderer.setRenderScale(state.renderScale);highFpsSamples=0;dirtyRender=true;}}
function loop(now){let realDt=Math.min((now-last)/1000,.12);last=now;if(now-fpsSince>900){state.fps=fpsFrames*1000/(now-fpsSince);fpsFrames=0;fpsSince=now;tuneRenderScale();}
 try{if(!state.paused&&!state.external){accumulator+=realDt*state.speed;let steps=0;while(accumulator>=1/30&&steps<32){simulationStep(1/30);accumulator-=1/30;steps++;}}if(state.auto&&!state.paused)state.az+=realDt*.085;if((!state.paused||dirtyRender)&&now-lastDraw>1000/72){render();fpsFrames++;dirtyRender=false;lastDraw=now;}uiClock+=realDt;if(uiClock>.13){uiClock=0;updateUI();}}catch(e){console.error(e);state.paused=true;toast(`실행 중 오류: ${e.message}`);}requestAnimationFrame(loop);}
addEventListener('resize',()=>dirtyRender=true);addEventListener('scroll',()=>dirtyRender=true,{passive:true});
requestAnimationFrame(loop);
})();
