/* FlyFight Zero — dependency-free WebGL2 renderer. Original implementation. */
'use strict';
const GFX = (() => {
 const V={add:(a,b)=>a.map((v,i)=>v+b[i]), sub:(a,b)=>a.map((v,i)=>v-b[i]), mul:(a,s)=>a.map(v=>v*s), dot:(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2], cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],norm:a=>{let l=Math.hypot(...a)||1;return a.map(v=>v/l);}};
 const I=()=>[1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1];
 const mul=(a,b)=>{const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++)for(let k=0;k<4;k++)o[c*4+r]+=a[k*4+r]*b[c*4+k];return o;};
 const T=(x,y,z)=>{let m=I();m[12]=x;m[13]=y;m[14]=z;return m;};
 const S=(x,y,z)=>[x,0,0,0,0,y,0,0,0,0,z,0,0,0,0,1];
 const RX=a=>[1,0,0,0,0,Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1];
 const RY=a=>[Math.cos(a),0,-Math.sin(a),0,0,1,0,0,Math.sin(a),0,Math.cos(a),0,0,0,0,1];
 const RZ=a=>[Math.cos(a),Math.sin(a),0,0,-Math.sin(a),Math.cos(a),0,0,0,0,1,0,0,0,0,1];
 const compose=(p,s=[1,1,1],r=[0,0,0])=>mul(T(...p),mul(RY(r[1]),mul(RX(r[0]),mul(RZ(r[2]),S(...s)))));
 const transform=(m,p)=>[m[0]*p[0]+m[4]*p[1]+m[8]*p[2]+m[12],m[1]*p[0]+m[5]*p[1]+m[9]*p[2]+m[13],m[2]*p[0]+m[6]*p[1]+m[10]*p[2]+m[14]];
 const lookAt=(eye,target)=>{let z=V.norm(V.sub(eye,target)),x=V.norm(V.cross([0,1,0],z)),y=V.cross(z,x);return [x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-V.dot(x,eye),-V.dot(y,eye),-V.dot(z,eye),1];};
 const perspective=(fov,aspect,near=.1,far=150)=>{let f=1/Math.tan(fov/2),nf=1/(near-far);return [f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0];};
 const color=(h,a=1)=>{h=h.replace('#','');return [parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255,a];};
 function sphere(u=18,v=12){let p=[],n=[],ind=[];for(let j=0;j<=v;j++)for(let i=0;i<=u;i++){let t=j/v*Math.PI,q=i/u*Math.PI*2,x=Math.sin(t)*Math.cos(q),y=Math.cos(t),z=Math.sin(t)*Math.sin(q);p.push(x,y,z);n.push(x,y,z);}for(let j=0;j<v;j++)for(let i=0;i<u;i++){let a=j*(u+1)+i,b=a+u+1;ind.push(a,b,a+1,b,b+1,a+1);}return {p,n,ind};}
 function box(){let p=[],n=[],ind=[];for(let axis=0;axis<3;axis++)for(let sign of [-1,1]){let u=(axis+1)%3,v=(axis+2)%3,k=p.length/3;for(let [a,b] of [[-1,-1],[1,-1],[1,1],[-1,1]]){let q=[0,0,0],nn=[0,0,0];q[axis]=sign*.5;q[u]=a*.5;q[v]=b*.5;nn[axis]=sign;p.push(...q);n.push(...nn);}if(sign===1)ind.push(k,k+1,k+2,k,k+2,k+3);else ind.push(k,k+2,k+1,k,k+3,k+2);}return {p,n,ind};}
 function cylinder(seg=12){let p=[],n=[],ind=[];for(let j=0;j<2;j++)for(let i=0;i<=seg;i++){let a=i/seg*Math.PI*2;p.push(Math.cos(a),j-.5,Math.sin(a));n.push(Math.cos(a),0,Math.sin(a));}for(let i=0;i<seg;i++)ind.push(i,i+seg+1,i+1,i+1,i+seg+1,i+seg+2);for(let top of [0,1]){let c=p.length/3;p.push(0,top-.5,0);n.push(0,top?1:-1,0);for(let i=0;i<=seg;i++){let a=i/seg*Math.PI*2;p.push(Math.cos(a),top-.5,Math.sin(a));n.push(0,top?1:-1,0);}for(let i=0;i<seg;i++)ind.push(c,c+i+1,c+i+2);}return {p,n,ind};}
 function ring(seg=64){let p=[],n=[],ind=[];for(let i=0;i<=seg;i++){let a=i/seg*Math.PI*2;for(let r of [.94,1]){p.push(Math.cos(a)*r,0,Math.sin(a)*r);n.push(0,1,0);}}for(let i=0;i<seg;i++){let k=i*2;ind.push(k,k+1,k+2,k+1,k+3,k+2);}return {p,n,ind};}
 const VS=`#version 300 es
 precision highp float;layout(location=0)in vec3 aPos;layout(location=1)in vec3 aNormal;layout(location=2)in mat4 aModel;layout(location=6)in vec4 aColor;layout(location=7)in float aKind;uniform mat4 uVP;out vec3 vPos;out vec3 vN;out vec4 vColor;out float vKind;
 void main(){vec4 p=aModel*vec4(aPos,1.);vPos=p.xyz;mat3 m=mat3(aModel);vN=normalize(m[0]*aNormal.x/max(dot(m[0],m[0]),.00001)+m[1]*aNormal.y/max(dot(m[1],m[1]),.00001)+m[2]*aNormal.z/max(dot(m[2],m[2]),.00001));vColor=aColor;vKind=aKind;gl_Position=uVP*p;}`;
 const FS=`#version 300 es
 precision highp float;in vec3 vPos;in vec3 vN;in vec4 vColor;in float vKind;uniform vec3 uEye;out vec4 frag;
 void main(){vec3 n=normalize(vN),view=normalize(uEye-vPos);float diffuse=max(dot(n,normalize(vec3(-.45,.9,.5))),0.);float back=max(dot(n,normalize(vec3(.65,.35,-.8))),0.);float spec=pow(max(dot(n,normalize(view+normalize(vec3(-.45,.9,.5)))),0.),32.);vec3 c=vColor.rgb*(.40+.68*diffuse+.24*back)+vec3(.22,.28,.34)*spec;
 if(vKind>1.5){c=vColor.rgb*1.28;}else if(vKind>.5){vec2 p=vPos.xz*.5;vec2 g=abs(fract(p-.5)-.5)/max(fwidth(p),vec2(.0001));float grid=1.-clamp(min(g.x,g.y),0.,1.);c=mix(c,c*.62,grid*.43);float radius=length(vPos.xz);c+=vec3(.04,.06,.08)*(1.-smoothstep(0.,14.,radius));}
 float fog=smoothstep(100.,240.,distance(uEye,vPos));c=mix(c,vec3(.035,.055,.075),fog);frag=vec4(c,vColor.a);}`;
 const PVS=`#version 300 es
 precision highp float;layout(location=0)in vec3 aPos;layout(location=1)in vec4 aColor;uniform mat4 uVP;uniform float uSize;out vec4 vColor;void main(){vec4 p=uVP*vec4(aPos,1.);gl_Position=p;gl_PointSize=uSize;vColor=aColor;}`;
 const PFS=`#version 300 es
 precision highp float;in vec4 vColor;out vec4 frag;uniform bool uPoint;void main(){float a=vColor.a;if(uPoint){float d=length(gl_PointCoord-.5)*2.;if(d>1.)discard;a*=pow(1.-d,1.3); }frag=vec4(vColor.rgb,a);}`;
 function program(gl,vs,fs){let p=gl.createProgram();for(let [type,src] of [[gl.VERTEX_SHADER,vs],[gl.FRAGMENT_SHADER,fs]]){let s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));gl.attachShader(p,s);}gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p));return p;}
 class Renderer{
 constructor(canvas){this.canvas=canvas;let gl=this.gl=canvas.getContext('webgl2',{alpha:false,antialias:true,preserveDrawingBuffer:true,powerPreference:'high-performance'});if(!gl)throw Error('WebGL 2를 사용할 수 없습니다. Chrome/Edge의 그래픽 가속 설정을 확인해 주세요.');this.prog=program(gl,VS,FS);this.pProg=program(gl,PVS,PFS);this.worldUniforms={vp:gl.getUniformLocation(this.prog,'uVP'),eye:gl.getUniformLocation(this.prog,'uEye')};this.pointUniforms={vp:gl.getUniformLocation(this.pProg,'uVP'),size:gl.getUniformLocation(this.pProg,'uSize'),point:gl.getUniformLocation(this.pProg,'uPoint')};this.meshes={};this.instances={};this.trans={};this.renderScale=1;this.neuralLines=new Float32Array(0);this.neuralPoints=new Float32Array(0);this.selectedPoint=new Float32Array(7);
 for(let [name,geo] of Object.entries({sphere:sphere(),small:sphere(10,7),box:box(),cylinder:cylinder(),ring:ring()})){let vao=gl.createVertexArray();gl.bindVertexArray(vao);for(let [loc,data]of[[0,geo.p],[1,geo.n]]){let b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,3,gl.FLOAT,false,0,0);}let ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(geo.ind),gl.STATIC_DRAW);let inst=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,inst);for(let j=0;j<4;j++){gl.enableVertexAttribArray(2+j);gl.vertexAttribPointer(2+j,4,gl.FLOAT,false,84,j*16);gl.vertexAttribDivisor(2+j,1);}gl.enableVertexAttribArray(6);gl.vertexAttribPointer(6,4,gl.FLOAT,false,84,64);gl.vertexAttribDivisor(6,1);gl.enableVertexAttribArray(7);gl.vertexAttribPointer(7,1,gl.FLOAT,false,84,80);gl.vertexAttribDivisor(7,1);this.meshes[name]={vao,inst,count:geo.ind.length,data:new Float32Array(0)};this.instances[name]=[];this.trans[name]=[];}
 this.pVao=gl.createVertexArray();gl.bindVertexArray(this.pVao);this.pBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,this.pBuffer);gl.enableVertexAttribArray(0);gl.vertexAttribPointer(0,3,gl.FLOAT,false,28,0);gl.enableVertexAttribArray(1);gl.vertexAttribPointer(1,4,gl.FLOAT,false,28,12);
 gl.enable(gl.DEPTH_TEST);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.disable(gl.CULL_FACE);gl.bindVertexArray(null);
 this.obsW=20;this.obsH=12;this.fbo=gl.createFramebuffer();gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo);let tex=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,tex);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,20,12,0,gl.RGBA,gl.UNSIGNED_BYTE,null);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.NEAREST);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.NEAREST);gl.framebufferTexture2D(gl.FRAMEBUFFER,gl.COLOR_ATTACHMENT0,gl.TEXTURE_2D,tex,0);let rb=gl.createRenderbuffer();gl.bindRenderbuffer(gl.RENDERBUFFER,rb);gl.renderbufferStorage(gl.RENDERBUFFER,gl.DEPTH_COMPONENT16,20,12);gl.framebufferRenderbuffer(gl.FRAMEBUFFER,gl.DEPTH_ATTACHMENT,gl.RENDERBUFFER,rb);if(gl.checkFramebufferStatus(gl.FRAMEBUFFER)!==gl.FRAMEBUFFER_COMPLETE)throw Error('시야 버퍼 초기화 실패');gl.bindFramebuffer(gl.FRAMEBUFFER,null);this.pixels=new Uint8Array(20*12*4);
 }
 setRenderScale(value){this.renderScale=Math.min(1,Math.max(.65,value));}
 resize(){let d=Math.min(devicePixelRatio||1,1.5)*this.renderScale,w=Math.floor(innerWidth*d),h=Math.floor(innerHeight*d),changed=this.canvas.width!==w||this.canvas.height!==h;if(changed){this.canvas.width=w;this.canvas.height=h;}this.dpr=d;return changed;}
 reset(){for(let k in this.instances){this.instances[k].length=0;this.trans[k].length=0;}}
 add(type,m,c,kind=0){(c[3]<.98?this.trans[type]:this.instances[type]).push(...m,...c,kind);}
 segment(a,b,r,c,kind=0){let y=V.norm(V.sub(b,a)),x=V.norm(V.cross(Math.abs(y[1])>.98?[1,0,0]:[0,1,0],y)),z=V.cross(x,y),len=Math.hypot(...V.sub(b,a)),mid=V.mul(V.add(a,b),.5);let m=[x[0]*r,x[1]*r,x[2]*r,0,y[0]*len,y[1]*len,y[2]*len,0,z[0]*r,z[1]*r,z[2]*r,0,...mid,1];this.add('cylinder',m,c,kind);}
 upload(){let gl=this.gl;for(let [name,data]of Object.entries(this.instances)){let m=this.meshes[name],transparent=this.trans[name],needed=data.length+transparent.length;m.opaque=data.length/21;m.trans=transparent.length/21;if(m.data.length<needed){let capacity=Math.max(256,m.data.length||256);while(capacity<needed)capacity*=2;m.data=new Float32Array(capacity);}m.data.set(data,0);m.data.set(transparent,data.length);gl.bindBuffer(gl.ARRAY_BUFFER,m.inst);gl.bufferData(gl.ARRAY_BUFFER,m.data.subarray(0,needed),gl.DYNAMIC_DRAW);}}
 instanceOffset(m,offset){let gl=this.gl;gl.bindVertexArray(m.vao);gl.bindBuffer(gl.ARRAY_BUFFER,m.inst);for(let j=0;j<4;j++)gl.vertexAttribPointer(2+j,4,gl.FLOAT,false,84,offset+j*16);gl.vertexAttribPointer(6,4,gl.FLOAT,false,84,offset+64);gl.vertexAttribPointer(7,1,gl.FLOAT,false,84,offset+80);}
 viewport(rect){let gl=this.gl,d=this.dpr;let x=Math.round(rect.left*d),y=Math.round((innerHeight-rect.bottom)*d),w=Math.max(1,Math.round(rect.width*d)),h=Math.max(1,Math.round(rect.height*d));gl.viewport(x,y,w,h);gl.scissor(x,y,w,h);gl.enable(gl.SCISSOR_TEST);return w/h;}
 clear(c=[.029,.044,.06,1]){let gl=this.gl;gl.clearColor(...c);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);}
 drawWorld(cam,aspect,clear=true){let gl=this.gl;if(clear)this.clear([.038,.061,.083,1]);gl.useProgram(this.prog);let vp=mul(perspective(cam.fov||.9,aspect),lookAt(cam.eye,cam.target));gl.uniformMatrix4fv(this.worldUniforms.vp,false,vp);gl.uniform3fv(this.worldUniforms.eye,cam.eye);gl.enable(gl.DEPTH_TEST);gl.depthMask(true);for(let m of Object.values(this.meshes)){if(!m.opaque)continue;this.instanceOffset(m,0);gl.drawElementsInstanced(gl.TRIANGLES,m.count,gl.UNSIGNED_SHORT,0,m.opaque);}gl.depthMask(false);for(let m of Object.values(this.meshes)){if(!m.trans)continue;this.instanceOffset(m,m.opaque*84);gl.drawElementsInstanced(gl.TRIANGLES,m.count,gl.UNSIGNED_SHORT,0,m.trans);}gl.depthMask(true);gl.bindVertexArray(null);}
 drawNeural(brain,rect,angle,selected=-1,options={}){let gl=this.gl,aspect=this.viewport(rect);this.clear([.025,.042,.059,1]);let zoom=Math.min(2.2,Math.max(.7,options.zoom||1)),dist=7.7*Math.max(1,1/aspect)/zoom,eye=[Math.sin(angle)*dist,1.3,Math.cos(angle)*dist],vp=mul(perspective(.73,aspect,.1,100),lookAt(eye,[0,0,0]));gl.useProgram(this.pProg);gl.uniformMatrix4fv(this.pointUniforms.vp,false,vp);gl.disable(gl.DEPTH_TEST);gl.depthMask(false);gl.bindVertexArray(this.pVao);
 let edgeMode=options.edges||'active',maxLines=edgeMode==='off'?0:brain.displayEdges.length*14,maxPoints=brain.n*7;if(this.neuralLines.length<maxLines)this.neuralLines=new Float32Array(Math.max(256,2**Math.ceil(Math.log2(maxLines||1))));if(this.neuralPoints.length<maxPoints)this.neuralPoints=new Float32Array(Math.max(256,2**Math.ceil(Math.log2(maxPoints||1))));let lineLength=0,pointLength=0,pal=brain.palette;if(edgeMode!=='off')for(let [i,j]of brain.displayEdges){let a=Math.max(brain.activity[i]||0,brain.activity[j]||0);if(edgeMode==='active'&&a<.07)continue;let shade=.50+.75*a,c=pal[brain.region[i]%pal.length]||pal[2],alpha=edgeMode==='all'?.035+a*.055:.025+a*.10;for(let k of [i,j]){let p=brain.pos[k];this.neuralLines[lineLength++]=p[0];this.neuralLines[lineLength++]=p[1];this.neuralLines[lineLength++]=p[2];this.neuralLines[lineLength++]=c[0]*shade;this.neuralLines[lineLength++]=c[1]*shade;this.neuralLines[lineLength++]=c[2]*shade;this.neuralLines[lineLength++]=alpha;}}for(let i=0;i<brain.n;i++){let a=Math.min(1,Math.max(0,brain.activity[i]||0)),shade=.50+.75*a,c=pal[brain.region[i]%pal.length]||pal[2],p=brain.pos[i];this.neuralPoints[pointLength++]=p[0];this.neuralPoints[pointLength++]=p[1];this.neuralPoints[pointLength++]=p[2];this.neuralPoints[pointLength++]=c[0]*shade;this.neuralPoints[pointLength++]=c[1]*shade;this.neuralPoints[pointLength++]=c[2]*shade;this.neuralPoints[pointLength++]=.32+a*.68;}
 gl.uniform1i(this.pointUniforms.point,0);gl.bindBuffer(gl.ARRAY_BUFFER,this.pBuffer);if(lineLength){gl.uniform1f(this.pointUniforms.size,this.dpr*4.8);gl.bufferData(gl.ARRAY_BUFFER,this.neuralLines.subarray(0,lineLength),gl.DYNAMIC_DRAW);gl.drawArrays(gl.LINES,0,lineLength/7);}gl.uniform1i(this.pointUniforms.point,1);gl.uniform1f(this.pointUniforms.size,this.dpr*6.2*(options.pointScale||1));gl.bufferData(gl.ARRAY_BUFFER,this.neuralPoints.subarray(0,pointLength),gl.DYNAMIC_DRAW);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.drawArrays(gl.POINTS,0,brain.n);if(selected>=0&&selected<brain.n){let p=brain.pos[selected],a=Math.min(1,Math.max(0,brain.activity[selected]||0));this.selectedPoint.set([p[0],p[1],p[2],1,.98,.68,.95]);gl.uniform1f(this.pointUniforms.size,this.dpr*13*(options.pointScale||1));gl.bufferData(gl.ARRAY_BUFFER,this.selectedPoint,gl.DYNAMIC_DRAW);gl.drawArrays(gl.POINTS,0,1);}gl.blendFunc(gl.SRC_ALPHA,gl.ONE_MINUS_SRC_ALPHA);gl.depthMask(true);gl.enable(gl.DEPTH_TEST);gl.bindVertexArray(null);return {vp,eye};}
 observe(cam){let gl=this.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,this.fbo);gl.disable(gl.SCISSOR_TEST);gl.viewport(0,0,20,12);this.drawWorld(cam,20/12);gl.readPixels(0,0,20,12,gl.RGBA,gl.UNSIGNED_BYTE,this.pixels);gl.bindFramebuffer(gl.FRAMEBUFFER,null);const p=new Float32Array(20*12*3);for(let i=0;i<240;i++)for(let c=0;c<3;c++)p[i*3+c]=this.pixels[i*4+c]/127.5-1;return p;}
 }
 return {Renderer,V,I,mul,T,S,RX,RY,RZ,compose,transform,lookAt,perspective,color};
})();
